/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevDashPreviewRouteImport } from './routes/dev-dash-preview'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReportsIndustryPdfRouteImport } from './routes/api/reports/industry-pdf'
import { Route as ApiChecklistsPreviewRouteImport } from './routes/api/checklists/preview'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDashPreviewRoute = DevDashPreviewRouteImport.update({
  id: '/dev-dash-preview',
  path: '/dev-dash-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsIndustryPdfRoute = ApiReportsIndustryPdfRouteImport.update({
  id: '/api/reports/industry-pdf',
  path: '/api/reports/industry-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChecklistsPreviewRoute = ApiChecklistsPreviewRouteImport.update({
  id: '/api/checklists/preview',
  path: '/api/checklists/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev-dash-preview': typeof DevDashPreviewRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/checklists/preview': typeof ApiChecklistsPreviewRoute
  '/api/reports/industry-pdf': typeof ApiReportsIndustryPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev-dash-preview': typeof DevDashPreviewRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/checklists/preview': typeof ApiChecklistsPreviewRoute
  '/api/reports/industry-pdf': typeof ApiReportsIndustryPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev-dash-preview': typeof DevDashPreviewRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/checklists/preview': typeof ApiChecklistsPreviewRoute
  '/api/reports/industry-pdf': typeof ApiReportsIndustryPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev-dash-preview'
    | '/login'
    | '/reset-password'
    | '/api/checklists/preview'
    | '/api/reports/industry-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev-dash-preview'
    | '/login'
    | '/reset-password'
    | '/api/checklists/preview'
    | '/api/reports/industry-pdf'
  id:
    | '__root__'
    | '/'
    | '/dev-dash-preview'
    | '/login'
    | '/reset-password'
    | '/api/checklists/preview'
    | '/api/reports/industry-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevDashPreviewRoute: typeof DevDashPreviewRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChecklistsPreviewRoute: typeof ApiChecklistsPreviewRoute
  ApiReportsIndustryPdfRoute: typeof ApiReportsIndustryPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-dash-preview': {
      id: '/dev-dash-preview'
      path: '/dev-dash-preview'
      fullPath: '/dev-dash-preview'
      preLoaderRoute: typeof DevDashPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/industry-pdf': {
      id: '/api/reports/industry-pdf'
      path: '/api/reports/industry-pdf'
      fullPath: '/api/reports/industry-pdf'
      preLoaderRoute: typeof ApiReportsIndustryPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checklists/preview': {
      id: '/api/checklists/preview'
      path: '/api/checklists/preview'
      fullPath: '/api/checklists/preview'
      preLoaderRoute: typeof ApiChecklistsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevDashPreviewRoute: DevDashPreviewRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChecklistsPreviewRoute: ApiChecklistsPreviewRoute,
  ApiReportsIndustryPdfRoute: ApiReportsIndustryPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
