/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Mk9PortalRouteImport } from './routes/mk9-portal'
import { Route as InteligenciaRouteImport } from './routes/inteligencia'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CockpitRouteImport } from './routes/cockpit'
import { Route as CleanupRouteImport } from './routes/cleanup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoteirosIndexRouteImport } from './routes/roteiros.index'
import { Route as RoteirosPromotorPromoterIdRouteImport } from './routes/roteiros.promotor.$promoterId'
import { Route as ApiReportsIndustryUnattendedPdfRouteImport } from './routes/api/reports/industry-unattended-pdf'
import { Route as ApiReportsIndustryPdfRouteImport } from './routes/api/reports/industry-pdf'
import { Route as ApiPublicMk9DebugImaginaRouteImport } from './routes/api/public/mk9-debug-imagina'
import { Route as ApiChecklistsPreviewRouteImport } from './routes/api/checklists/preview'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Mk9PortalRoute = Mk9PortalRouteImport.update({
  id: '/mk9-portal',
  path: '/mk9-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaRoute = InteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CockpitRoute = CockpitRouteImport.update({
  id: '/cockpit',
  path: '/cockpit',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanupRoute = CleanupRouteImport.update({
  id: '/cleanup',
  path: '/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteirosIndexRoute = RoteirosIndexRouteImport.update({
  id: '/roteiros/',
  path: '/roteiros/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteirosPromotorPromoterIdRoute =
  RoteirosPromotorPromoterIdRouteImport.update({
    id: '/roteiros/promotor/$promoterId',
    path: '/roteiros/promotor/$promoterId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiReportsIndustryUnattendedPdfRoute =
  ApiReportsIndustryUnattendedPdfRouteImport.update({
    id: '/api/reports/industry-unattended-pdf',
    path: '/api/reports/industry-unattended-pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiReportsIndustryPdfRoute = ApiReportsIndustryPdfRouteImport.update({
  id: '/api/reports/industry-pdf',
  path: '/api/reports/industry-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMk9DebugImaginaRoute =
  ApiPublicMk9DebugImaginaRouteImport.update({
    id: '/api/public/mk9-debug-imagina',
    path: '/api/public/mk9-debug-imagina',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChecklistsPreviewRoute = ApiChecklistsPreviewRouteImport.update({
  id: '/api/checklists/preview',
  path: '/api/checklists/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cleanup': typeof CleanupRoute
  '/cockpit': typeof CockpitRoute
  '/dashboard': typeof DashboardRoute
  '/inteligencia': typeof InteligenciaRoute
  '/mk9-portal': typeof Mk9PortalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/users': typeof UsersRoute
  '/roteiros/': typeof RoteirosIndexRoute
  '/api/checklists/preview': typeof ApiChecklistsPreviewRoute
  '/api/public/mk9-debug-imagina': typeof ApiPublicMk9DebugImaginaRoute
  '/api/reports/industry-pdf': typeof ApiReportsIndustryPdfRoute
  '/api/reports/industry-unattended-pdf': typeof ApiReportsIndustryUnattendedPdfRoute
  '/roteiros/promotor/$promoterId': typeof RoteirosPromotorPromoterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cleanup': typeof CleanupRoute
  '/cockpit': typeof CockpitRoute
  '/dashboard': typeof DashboardRoute
  '/inteligencia': typeof InteligenciaRoute
  '/mk9-portal': typeof Mk9PortalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/users': typeof UsersRoute
  '/roteiros': typeof RoteirosIndexRoute
  '/api/checklists/preview': typeof ApiChecklistsPreviewRoute
  '/api/public/mk9-debug-imagina': typeof ApiPublicMk9DebugImaginaRoute
  '/api/reports/industry-pdf': typeof ApiReportsIndustryPdfRoute
  '/api/reports/industry-unattended-pdf': typeof ApiReportsIndustryUnattendedPdfRoute
  '/roteiros/promotor/$promoterId': typeof RoteirosPromotorPromoterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cleanup': typeof CleanupRoute
  '/cockpit': typeof CockpitRoute
  '/dashboard': typeof DashboardRoute
  '/inteligencia': typeof InteligenciaRoute
  '/mk9-portal': typeof Mk9PortalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/users': typeof UsersRoute
  '/roteiros/': typeof RoteirosIndexRoute
  '/api/checklists/preview': typeof ApiChecklistsPreviewRoute
  '/api/public/mk9-debug-imagina': typeof ApiPublicMk9DebugImaginaRoute
  '/api/reports/industry-pdf': typeof ApiReportsIndustryPdfRoute
  '/api/reports/industry-unattended-pdf': typeof ApiReportsIndustryUnattendedPdfRoute
  '/roteiros/promotor/$promoterId': typeof RoteirosPromotorPromoterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cleanup'
    | '/cockpit'
    | '/dashboard'
    | '/inteligencia'
    | '/mk9-portal'
    | '/reset-password'
    | '/users'
    | '/roteiros/'
    | '/api/checklists/preview'
    | '/api/public/mk9-debug-imagina'
    | '/api/reports/industry-pdf'
    | '/api/reports/industry-unattended-pdf'
    | '/roteiros/promotor/$promoterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cleanup'
    | '/cockpit'
    | '/dashboard'
    | '/inteligencia'
    | '/mk9-portal'
    | '/reset-password'
    | '/users'
    | '/roteiros'
    | '/api/checklists/preview'
    | '/api/public/mk9-debug-imagina'
    | '/api/reports/industry-pdf'
    | '/api/reports/industry-unattended-pdf'
    | '/roteiros/promotor/$promoterId'
  id:
    | '__root__'
    | '/'
    | '/cleanup'
    | '/cockpit'
    | '/dashboard'
    | '/inteligencia'
    | '/mk9-portal'
    | '/reset-password'
    | '/users'
    | '/roteiros/'
    | '/api/checklists/preview'
    | '/api/public/mk9-debug-imagina'
    | '/api/reports/industry-pdf'
    | '/api/reports/industry-unattended-pdf'
    | '/roteiros/promotor/$promoterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CleanupRoute: typeof CleanupRoute
  CockpitRoute: typeof CockpitRoute
  DashboardRoute: typeof DashboardRoute
  InteligenciaRoute: typeof InteligenciaRoute
  Mk9PortalRoute: typeof Mk9PortalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UsersRoute: typeof UsersRoute
  RoteirosIndexRoute: typeof RoteirosIndexRoute
  ApiChecklistsPreviewRoute: typeof ApiChecklistsPreviewRoute
  ApiPublicMk9DebugImaginaRoute: typeof ApiPublicMk9DebugImaginaRoute
  ApiReportsIndustryPdfRoute: typeof ApiReportsIndustryPdfRoute
  ApiReportsIndustryUnattendedPdfRoute: typeof ApiReportsIndustryUnattendedPdfRoute
  RoteirosPromotorPromoterIdRoute: typeof RoteirosPromotorPromoterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mk9-portal': {
      id: '/mk9-portal'
      path: '/mk9-portal'
      fullPath: '/mk9-portal'
      preLoaderRoute: typeof Mk9PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia': {
      id: '/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof InteligenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cockpit': {
      id: '/cockpit'
      path: '/cockpit'
      fullPath: '/cockpit'
      preLoaderRoute: typeof CockpitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleanup': {
      id: '/cleanup'
      path: '/cleanup'
      fullPath: '/cleanup'
      preLoaderRoute: typeof CleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteiros/': {
      id: '/roteiros/'
      path: '/roteiros'
      fullPath: '/roteiros/'
      preLoaderRoute: typeof RoteirosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteiros/promotor/$promoterId': {
      id: '/roteiros/promotor/$promoterId'
      path: '/roteiros/promotor/$promoterId'
      fullPath: '/roteiros/promotor/$promoterId'
      preLoaderRoute: typeof RoteirosPromotorPromoterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/industry-unattended-pdf': {
      id: '/api/reports/industry-unattended-pdf'
      path: '/api/reports/industry-unattended-pdf'
      fullPath: '/api/reports/industry-unattended-pdf'
      preLoaderRoute: typeof ApiReportsIndustryUnattendedPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/industry-pdf': {
      id: '/api/reports/industry-pdf'
      path: '/api/reports/industry-pdf'
      fullPath: '/api/reports/industry-pdf'
      preLoaderRoute: typeof ApiReportsIndustryPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mk9-debug-imagina': {
      id: '/api/public/mk9-debug-imagina'
      path: '/api/public/mk9-debug-imagina'
      fullPath: '/api/public/mk9-debug-imagina'
      preLoaderRoute: typeof ApiPublicMk9DebugImaginaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checklists/preview': {
      id: '/api/checklists/preview'
      path: '/api/checklists/preview'
      fullPath: '/api/checklists/preview'
      preLoaderRoute: typeof ApiChecklistsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CleanupRoute: CleanupRoute,
  CockpitRoute: CockpitRoute,
  DashboardRoute: DashboardRoute,
  InteligenciaRoute: InteligenciaRoute,
  Mk9PortalRoute: Mk9PortalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UsersRoute: UsersRoute,
  RoteirosIndexRoute: RoteirosIndexRoute,
  ApiChecklistsPreviewRoute: ApiChecklistsPreviewRoute,
  ApiPublicMk9DebugImaginaRoute: ApiPublicMk9DebugImaginaRoute,
  ApiReportsIndustryPdfRoute: ApiReportsIndustryPdfRoute,
  ApiReportsIndustryUnattendedPdfRoute: ApiReportsIndustryUnattendedPdfRoute,
  RoteirosPromotorPromoterIdRoute: RoteirosPromotorPromoterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
