export const Constants = {
    public: {
        Enums: {
            mk9_actual_visit_origin: ["CHECKLIST"],
            mk9_import_status: [
                "pending",
                "previewing",
                "confirmed",
                "committing",
                "done",
                "failed",
                "cancelled",
                "INCONSISTENT",
                "COMPLETED_WITH_ALERTS",
            ],
            mk9_industry_control_mode: ["VISIT_CONTROLLED", "FIXED_OPERATION"],
            mk9_industry_status: [
                "DENTRO DA META",
                "ACIMA DA META",
                "ABAIXO DA META",
                "SEM META",
                "OK",
            ],
            mk9_period_type: ["CALENDAR_MONTH", "CUSTOM_CYCLE"],
            mk9_reconciliation_match_type: ["EXACT", "NEAR_DATE", "MANUAL", "NONE"],
            mk9_reconciliation_status: [
                "MATCHED",
                "DATE_DIVERGENCE",
                "UNPLANNED_VISIT",
                "NOT_COMPLETED",
                "STORE_NOT_FOUND",
                "AMBIGUOUS",
                "DUPLICATE_ACTUAL",
                "MANUALLY_MATCHED",
                "IGNORED",
            ],
            mk9_role: ["ADMIN", "SUPERVISOR", "PROMOTOR", "CLIENTE", "AUDITOR"],
            mk9_sync_mode: ["full", "add_only", "registry_only", "routes_only"],
            mk9_visit_status: ["planned", "completed", "cancelled", "skipped"],
            mk9_week_grouping: ["CALENDAR_WEEK", "CYCLE_WEEK"],
        },
    },
};
